In [29]:
import numpy as np  #package numpy can also be reffered as np. It has functions for working in domain of linear algebra,and matrices. 
import pandas as pd  #package pandas can also be refferd as pd. It has functions for analyzing, cleaning and manipulating data.
from scipy.io import arff  #SciPy has many modules, classes, and functions to read and write data to a variety of file formats.
from sklearn.naive_bayes import GaussianNB  #Naive Bayes is a statistical classification technique based on Bayes Theorem and GaussianNB is bassed on classification technique used in machine learning based on the probabilistic approach 
from sklearn.model_selection import train_test_split  # sklearn.model_selection split our data into train and test sets where feature variables are given as input in the method.
from sklearn.preprocessing import LabelEncoder  #Label Encoding is a technique that is used to convert categorical columns into numerical ones.
from sklearn.metrics import accuracy_score, classification_report  #sklearn.metrics module implements several loss, score, and utility functions to measure classification performance.


In [30]:
#df=pd.read_csv(r'C:\Users\V. K. Srivastava\Desktop\autism1.csv')
data = arff.loadarff(r"C:\Users\V. K. Srivastava\Desktop\Autism-Adolescent-Data.arff")  #used to load the path of arff file.
df = pd.DataFrame(data[0])  #pd.df is a two-dimensional, tabular data. data structure constructed with rows and columns.

In [31]:
df.head() # method returns a specified number of rows, string from the top.

A1_Score A2_Score A3_Score A4_Score A5_Score A6_Score A7_Score A8_Score  \
0     b'0'     b'0'     b'0'     b'1'     b'1'     b'1'     b'1'     b'1'   
1     b'0'     b'0'     b'0'     b'0'     b'0'     b'0'     b'0'     b'0'   
2     b'0'     b'0'     b'0'     b'0'     b'0'     b'0'     b'0'     b'0'   
3     b'0'     b'1'     b'1'     b'1'     b'1'     b'1'     b'0'     b'1'   
4     b'1'     b'1'     b'1'     b'1'     b'1'     b'1'     b'1'     b'0'   

  A9_Score A10_Score  ...  gender          ethnicity jundice  austim  \
0     b'1'      b'0'  ...    b'm'        b'Hispanic'  b'yes'  b'yes'   
1     b'1'      b'1'  ...    b'm'           b'Black'   b'no'   b'no'   
2     b'1'      b'1'  ...    b'f'               b'?'   b'no'   b'no'   
3     b'1'      b'0'  ...    b'f'  b'White-European'   b'no'   b'no'   
4     b'0'      b'0'  ...    b'f'               b'?'   b'no'   b'no'   

       contry_of_res used_app_before result        age_desc     relation  \
0         b'Austria'           b'no'    6.0  b'12-16 years'    b'Parent'   
1         b'Austria'           b'no'    2.0  b'12-16 years'  b'Relative'   
2   b'AmericanSamoa'           b'no'    2.0  b'12-16 years'         b'?'   
3  b'United Kingdom'           b'no'    7.0  b'12-16 years'      b'Self'   
4         b'Albania'           b'no'    7.0  b'12-16 years'         b'?'   

  Class/ASD  
0     b'NO'  
1     b'NO'  
2     b'NO'  
3    b'YES'  
4    b'YES'  

[5 rows x 21 columns]

In [32]:
for column in df.select_dtypes([object]):  #method returns a new DataFrame that includes/excludes columns of the specified dtype
    df[column] = df[column].str.decode('utf-8')  # df[column] provides access to the column labels of a data frame and utf-8 is  used to decode the encoded form of a string

In [33]:
df.head()  #method returns a specified number of rows, string from the top.

A1_Score A2_Score A3_Score A4_Score A5_Score A6_Score A7_Score A8_Score  \
0        0        0        0        1        1        1        1        1   
1        0        0        0        0        0        0        0        0   
2        0        0        0        0        0        0        0        0   
3        0        1        1        1        1        1        0        1   
4        1        1        1        1        1        1        1        0   

  A9_Score A10_Score  ...  gender       ethnicity jundice austim  \
0        1         0  ...       m        Hispanic     yes    yes   
1        1         1  ...       m           Black      no     no   
2        1         1  ...       f               ?      no     no   
3        1         0  ...       f  White-European      no     no   
4        0         0  ...       f               ?      no     no   

    contry_of_res used_app_before result     age_desc  relation Class/ASD  
0         Austria              no    6.0  12-16 years    Parent        NO  
1         Austria              no    2.0  12-16 years  Relative        NO  
2   AmericanSamoa              no    2.0  12-16 years         ?        NO  
3  United Kingdom              no    7.0  12-16 years      Self       YES  
4         Albania              no    7.0  12-16 years         ?       YES  

[5 rows x 21 columns]

In [34]:
# Encode categorical columns
label_encoders = {}  # used to convert categorical columns into numerical format.
for column in df.select_dtypes([object]).columns:  # provides access to the column labels of a data frame.
    label_encoders[column] = LabelEncoder() 
    df[column] = label_encoders[column].fit_transform(df[column]) #fit_transform is used to fit data into a model and transform it into more suitable  model in a single step

In [35]:
df.head()  # method returns a specified number of rows, string from the top.

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0         0         0         0         1         1         1         1   
1         0         0         0         0         0         0         0   
2         0         0         0         0         0         0         0   
3         0         1         1         1         1         1         0   
4         1         1         1         1         1         1         1   

   A8_Score  A9_Score  A10_Score  ...  gender  ethnicity  jundice  austim  \
0         1         1          0  ...       1          3        1       1   
1         0         1          1  ...       1          2        0       0   
2         0         1          1  ...       0          0        0       0   
3         1         1          0  ...       0          8        0       0   
4         0         0          0  ...       0          0        0       0   

   contry_of_res  used_app_before  result  age_desc  relation  Class/ASD  
0              6                0     6.0         1         3          0  
1              6                0     2.0         1         4          0  
2              2                0     2.0         1         0          0  
3             30                0     7.0         1         5          1  
4              1                0     7.0         1         0          1  

[5 rows x 21 columns]

In [36]:
# Preparing features and target variables
X = df.iloc[:, :-1].values  # Features: all columns except the last one
y = df.iloc[:, -1].values   # Target variable: the last column

In [37]:
X  # print features and target variables of X

array([[0., 0., 0., ..., 6., 1., 3.],
       [0., 0., 0., ..., 2., 1., 4.],
       [0., 0., 0., ..., 2., 1., 0.],
       ...,
       [1., 0., 0., ..., 8., 1., 5.],
       [1., 1., 0., ..., 6., 1., 5.],
       [1., 0., 1., ..., 6., 1., 3.]])

In [38]:
y  # print features and target variables of y

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0])

In [39]:
# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)  
# test_size indicates the percentage of the data that should be held over for testing
# random_test controls the random shuffling and splitting of data. We get the same train and test sets across different executions

In [40]:
X_train  # training and fitting data set, used to train a model

array([[ 0.,  0.,  0., ...,  3.,  1.,  5.],
       [ 1.,  1.,  1., ..., 10.,  1.,  3.],
       [ 1.,  1.,  1., ...,  9.,  1.,  3.],
       ...,
       [ 1.,  0.,  1., ...,  4.,  1.,  4.],
       [ 0.,  1.,  1., ...,  9.,  1.,  3.],
       [ 1.,  1.,  0., ...,  6.,  1.,  5.]])

In [41]:
y_train  # training data set. It is a dependent variable which needs to be predicted by this model,

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0])

In [42]:
# Initialize the Gaussian Naive Bayes classifier
clf = GaussianNB() #  classification of a probability distribution (GaussianNB).

In [43]:
clf

GaussianNB()

In [44]:
# Train the model
clf.fit(X_train, y_train)  #.fit is used to train a machine learning model on a dataset.


GaussianNB()

In [45]:
# Make predictions on the test set
y_pred = clf.predict(X_test)  # used to get the predictions for the data we have trained with

In [46]:
y_pred  #the data predicted (calculated, output) by your model, or estimate based on the patterns it has learned from the training data

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0])

In [47]:
y_test  #  contains the target output

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0])

In [48]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)  #computes subset accuracy the set of labels predicted for sample must exactly match the corresponding set of labels
report = classification_report(y_test, y_pred)  # classification_report shows the main metrics for each class of a machine learning model


In [49]:
accuracy   #accuracy = (number of correct predictions) / (total number of predictions) 

0.9047619047619048

In [50]:
# Print the results
print(f'Accuracy: {accuracy:.2f}')
print('Classification Report:')
print(report)
# Precision: It can be seen as a measure of quality Higher precision means that an algorithm returns more relevant results.
# Recall: The ability of a model to correctly find all relevent positive instances within a dataset.
# f1-score: It is the harmonic mean of precision and recall. It minimizes false positives and ensures the positive predictions.
# Support: the number of actual occurrences of the class in the dataset.

Accuracy: 0.90
Classification Report:
              precision    recall  f1-score   support

           0       0.80      1.00      0.89         8
           1       1.00      0.85      0.92        13

    accuracy                           0.90        21
   macro avg       0.90      0.92      0.90        21
weighted avg       0.92      0.90      0.91        21



In [51]:
# Display DataFrame head and descriptive statistics from the top.
print(df.head())

   A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0         0         0         0         1         1         1         1   
1         0         0         0         0         0         0         0   
2         0         0         0         0         0         0         0   
3         0         1         1         1         1         1         0   
4         1         1         1         1         1         1         1   

   A8_Score  A9_Score  A10_Score  ...  gender  ethnicity  jundice  austim  \
0         1         1          0  ...       1          3        1       1   
1         0         1          1  ...       1          2        0       0   
2         0         1          1  ...       0          0        0       0   
3         1         1          0  ...       0          8        0       0   
4         0         0          0  ...       0          0        0       0   

   contry_of_res  used_app_before  result  age_desc  relation  Class/ASD  
0          

In [53]:
print(df.describe())  # Returns description of the data in the DataFrame

         A1_Score    A2_Score    A3_Score    A4_Score   A5_Score    A6_Score  \
count  104.000000  104.000000  104.000000  104.000000  104.00000  104.000000   
mean     0.730769    0.538462    0.653846    0.701923    0.75000    0.769231   
std      0.445708    0.500933    0.478047    0.459629    0.43511    0.423365   
min      0.000000    0.000000    0.000000    0.000000    0.00000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.75000    1.000000   
50%      1.000000    1.000000    1.000000    1.000000    1.00000    1.000000   
75%      1.000000    1.000000    1.000000    1.000000    1.00000    1.000000   
max      1.000000    1.000000    1.000000    1.000000    1.00000    1.000000   

         A7_Score    A8_Score    A9_Score   A10_Score  ...      gender  \
count  104.000000  104.000000  104.000000  104.000000  ...  104.000000   
mean     0.519231    0.615385    0.788462    0.653846  ...    0.480769   
std      0.502050    0.488860    0.410377    0.478047  ..